# Generated by Django 4.1.5 on 2023-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_auto_author_auto_anno_alter_auto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
