# Generated by Django 4.1.5 on 2023-06-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(default='enProceso.png', upload_to=''),
        ),
    ]
