# Generated by Django 4.1.5 on 2023-06-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_auto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('appaterno', models.CharField(max_length=200)),
                ('apmaterno', models.CharField(max_length=200)),
                ('run', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fecha_nac', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
    ]
