# Generated by Django 4.1.5 on 2023-06-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.IntegerField(choices=[[0, 'Hombre'], [1, 'Mujer'], [2, 'Otro']]),
        ),
    ]
