# Generated by Django 4.1.5 on 2023-06-29 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_cliente_email_alter_cliente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
