# Generated by Django 4.1.5 on 2023-06-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_cliente_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
