# Generated by Django 4.1.5 on 2023-06-29 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_cliente_fecha_nac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='enProceso.png', upload_to='')),
                ('marca', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
    ]
