# Generated by Django 4.1.5 on 2023-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='enProceso.png', null=True, upload_to=''),
        ),
    ]
