# Generated by Django 4.1.5 on 2023-07-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(default='enProceso.png', upload_to='Autos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='enProceso.png', null=True, upload_to='Productos'),
        ),
        migrations.CreateModel(
            name='ImagenAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Autos')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.auto')),
            ],
        ),
    ]
