# Generated by Django 4.1.5 on 2023-07-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_auto_imagen_alter_producto_imagen_imagenauto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenauto',
            name='auto',
            field=models.ForeignKey(default='giphy.webp', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web.auto'),
        ),
    ]
