# Generated by Django 4.1.5 on 2023-07-08 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_auto_imagen_auto_cilindrada_auto_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cilindrada',
            field=models.CharField(default='Sin Especificar', max_length=200),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
