# Generated by Django 4.1.5 on 2023-07-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_auto_cilindrada_alter_auto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(default='giphy.webp', upload_to='Autos'),
        ),
    ]
