# Generated by Django 4.1.5 on 2023-07-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='nombre',
        ),
    ]
